version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  version: 2
  scan-workflow:
    jobs:
      - sonarcloud/scan:
          organization: sibacode
          project-key: SibaCode_POE_APDS
          project-name: "SibaCode_POE_APDS"
